apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: "$POSTGRES_URL"
    database: "$POSTGRES_DB"
    user: "$POSTGRES_USER"
    secureJsonData:
      password: "$POSTGRES_PASS"
    jsonData:
      sslmode: "$POSTGRES_SSL_MODE"
      timescaledb: false

  - name: Prometheus
    type: prometheus
    url: "$PROMETHEUS_URL"
    access: "proxy"
    basicAuth: false
